import Foundation

/// Generates JSFX effects (REAPER's script format, also hosted by EffectDeck on iOS) that apply presets
/// exactly as `EQProcessor` does: the preamp, then each enabled filter as an Audio EQ Cookbook biquad in
/// transposed direct form II, in 64-bit arithmetic. Coefficients are computed from the host's sample rate
/// with the same expressions, in the same order, as `BiquadCoefficients`.
public enum JSFXExport {
    /// One effect with a selector for `presets`. Hosts that identify scripts by `desc` (EffectDeck does)
    /// replace an earlier import with the same `title`, so re-exporting updates the effect in place.
    public static func script(presets: [ParametricPreset], title: String) -> String {
        precondition(!presets.isEmpty, "A JSFX needs at least one preset")
        let selectorHidden = presets.count == 1 ? "-" : ""

        var data: [String] = []
        for (index, preset) in presets.enumerated() {
            let enabled = preset.filters.filter(\.isEnabled).prefix(EQProcessor.maxFilters)
            data.append("// \(index): \(preset.name)")
            data.append("preset(\(index), \(enabled.count), \(number(preset.preampDB)));")
            for (band, filter) in enabled.enumerated() {
                data.append("band(\(index), \(band), \(typeCode(filter.type)), \(number(filter.frequency)), \(number(filter.gainDB)), \(number(filter.q)));")
            }
        }

        return """
        desc:SystemEQ: \(singleLine(title))
        author:SystemEQ
        //tags: equalizer parametric
        // Generated by SystemEQ (https://github.com/naught9/SystemEQ) from \(presets.count) preset\(presets.count == 1 ? "" : "s").
        // Applies the selected preset's preamp, then its filters as Audio EQ Cookbook biquads in transposed
        // direct form II, computed for the host's sample rate exactly as SystemEQ's EQProcessor does.

        slider1:0<0,\(presets.count - 1),1{\(presets.map { menuLabel($0.name) }.joined(separator: ","))}>\(selectorHidden)Preset
        slider2:0<-30,30,0.01>Preamp adjust (dB)

        in_pin:left
        in_pin:right
        out_pin:left
        out_pin:right

        @init
        presetCount = \(presets.count);
        maxBands = 64;
        maxChannels = 8;
        // Coefficients of the loaded preset, filter state per channel, then each preset's settings:
        // [band count, preamp, then type, frequency, gain, Q for each band].
        cb0 = 0; cb1 = 64; cb2 = 128; ca1 = 192; ca2 = 256;
        s1 = 1024; s2 = s1 + maxBands * maxChannels;
        presets = 8192; presetSize = 2 + 4 * maxBands;

        function preset(p, count, preampDB) local(o) (
          o = presets + p * presetSize;
          o[0] = count; o[1] = preampDB;
        );

        function band(p, j, t, f, g, qq) local(o) (
          o = presets + p * presetSize + 2 + j * 4;
          o[0] = t; o[1] = f; o[2] = g; o[3] = qq;
        );

        // BiquadCoefficients(filter:sampleRate:): identity for bands the sample rate can't realise.
        function design(i, t, f, g, qq) local(w0, cosW0, alpha, a, s, b0, b1, b2, a0, a1, a2) (
          f > 0 && f < srate / 2 && qq > 0 ? (
            w0 = 2 * $pi * f / srate;
            cosW0 = cos(w0);
            alpha = sin(w0) / (2 * qq);
            a = 10 ^ (g / 40);
            t == 0 ? (
              b0 = 1 + alpha * a; b1 = -2 * cosW0; b2 = 1 - alpha * a;
              a0 = 1 + alpha / a; a1 = -2 * cosW0; a2 = 1 - alpha / a;
            ) : t == 1 ? (
              s = 2 * sqrt(a) * alpha;
              b0 = a * ((a + 1) - (a - 1) * cosW0 + s);
              b1 = 2 * a * ((a - 1) - (a + 1) * cosW0);
              b2 = a * ((a + 1) - (a - 1) * cosW0 - s);
              a0 = (a + 1) + (a - 1) * cosW0 + s;
              a1 = -2 * ((a - 1) + (a + 1) * cosW0);
              a2 = (a + 1) + (a - 1) * cosW0 - s;
            ) : t == 2 ? (
              s = 2 * sqrt(a) * alpha;
              b0 = a * ((a + 1) + (a - 1) * cosW0 + s);
              b1 = -2 * a * ((a - 1) + (a + 1) * cosW0);
              b2 = a * ((a + 1) + (a - 1) * cosW0 - s);
              a0 = (a + 1) - (a - 1) * cosW0 + s;
              a1 = 2 * ((a - 1) - (a + 1) * cosW0);
              a2 = (a + 1) - (a - 1) * cosW0 - s;
            ) : t == 3 ? (
              b0 = (1 - cosW0) / 2; b1 = 1 - cosW0; b2 = (1 - cosW0) / 2;
              a0 = 1 + alpha; a1 = -2 * cosW0; a2 = 1 - alpha;
            ) : t == 4 ? (
              b0 = (1 + cosW0) / 2; b1 = -(1 + cosW0); b2 = (1 + cosW0) / 2;
              a0 = 1 + alpha; a1 = -2 * cosW0; a2 = 1 - alpha;
            ) : (
              b0 = 1; b1 = -2 * cosW0; b2 = 1;
              a0 = 1 + alpha; a1 = -2 * cosW0; a2 = 1 - alpha;
            );
            cb0[i] = b0 / a0; cb1[i] = b1 / a0; cb2[i] = b2 / a0; ca1[i] = a1 / a0; ca2[i] = a2 / a0;
          ) : (
            cb0[i] = 1; cb1[i] = 0; cb2[i] = 0; ca1[i] = 0; ca2[i] = 0;
          );
        );

        // Like EQProcessor.setPreset, switching presets keeps the filter state.
        function load(p) local(o, j) (
          o = presets + p * presetSize;
          bandCount = o[0];
          presetPreampDB = o[1];
          j = 0;
          loop(bandCount,
            design(j, o[2 + j * 4], o[3 + j * 4], o[4 + j * 4], o[5 + j * 4]);
            j += 1;
          );
        );

        \(data.joined(separator: "\n"))

        memset(s1, 0, 2 * maxBands * maxChannels);
        loaded = -1;

        @slider
        selected = min(max(floor(slider1 + 0.5), 0), presetCount - 1);
        selected != loaded ? (
          load(selected);
          loaded = selected;
        );
        gain = 10 ^ ((presetPreampDB + slider2) / 20);

        @sample
        // Always on: bypass the whole effect in the host to compare.
        ch = 0;
        loop(min(num_ch, maxChannels),
          x = spl(ch) * gain;
          i = 0;
          loop(bandCount,
            k = ch * maxBands + i;
            y = cb0[i] * x + s1[k];
            s1[k] = cb1[i] * x - ca1[i] * y + s2[k];
            s2[k] = cb2[i] * x - ca2[i] * y;
            x = y;
            i += 1;
          );
          spl(ch) = x;
          ch += 1;
        );

        """
    }

    /// Swift prints the shortest text that parses back to the same double, so the script holds exactly
    /// the presets' values while staying readable.
    static func number(_ value: Double) -> String {
        value == value.rounded() && abs(value) < 1e15 ? String(Int(value)) : "\(value)"
    }

    static func typeCode(_ type: FilterType) -> Int {
        switch type {
        case .peaking: 0
        case .lowShelf: 1
        case .highShelf: 2
        case .lowPass: 3
        case .highPass: 4
        case .notch: 5
        }
    }

    /// A preset name usable inside a slider's `{…}` menu, where `,` separates entries and `<`, `>`, `{`, `}`
    /// delimit the slider definition.
    static func menuLabel(_ name: String) -> String {
        singleLine(name)
            .replacingOccurrences(of: "->", with: "→")
            .replacingOccurrences(of: ",", with: ";")
            .replacingOccurrences(of: "<", with: "(")
            .replacingOccurrences(of: ">", with: ")")
            .replacingOccurrences(of: "{", with: "(")
            .replacingOccurrences(of: "}", with: ")")
    }

    private static func singleLine(_ text: String) -> String {
        text.replacingOccurrences(of: "\n", with: " ").replacingOccurrences(of: "\r", with: " ")
    }
}

extension ParametricPreset {
    /// A JSFX effect applying just this preset, named after it.
    public var jsfxScript: String {
        JSFXExport.script(presets: [self], title: name)
    }
}
