import Foundation

extension ParametricPreset {
    /// A self-contained JSFX effect (REAPER's script format, also hosted by EffectDeck on iOS) that applies
    /// this preset exactly as `EQProcessor` does: the preamp, then each enabled filter as an Audio EQ Cookbook
    /// biquad in transposed direct form II, in 64-bit arithmetic. Coefficients are computed from the host's
    /// sample rate with the same expressions, in the same order, as `BiquadCoefficients`.
    public var jsfxScript: String {
        let enabled = filters.filter(\.isEnabled).prefix(EQProcessor.maxFilters)
        // Swift prints the shortest text that parses back to the same double, so the script holds
        // exactly the preset's values while staying readable.
        func number(_ value: Double) -> String {
            value == value.rounded() && abs(value) < 1e15 ? String(Int(value)) : "\(value)"
        }
        func typeCode(_ type: FilterType) -> Int {
            switch type {
            case .peaking: 0
            case .lowShelf: 1
            case .highShelf: 2
            case .lowPass: 3
            case .highPass: 4
            case .notch: 5
            }
        }
        let bands = enabled.enumerated().map { index, filter in
            "band(\(index), \(typeCode(filter.type)), \(number(filter.frequency)), \(number(filter.gainDB)), \(number(filter.q)));"
        }

        return """
        desc:SystemEQ: \(name.replacingOccurrences(of: "\n", with: " "))
        author:SystemEQ
        //tags: equalizer parametric
        // Generated by SystemEQ (https://github.com/naught9/SystemEQ) from the preset "\(name)".
        // Applies the preamp, then \(enabled.count) Audio EQ Cookbook biquads in transposed direct form II,
        // computed for the host's sample rate exactly as SystemEQ's EQProcessor does.

        slider1:\(number(preampDB))<-30,30,0.01>Preamp (dB)
        slider2:0<0,1,1{On,Bypassed}>EQ

        in_pin:left
        in_pin:right
        out_pin:left
        out_pin:right

        @init
        bandCount = \(enabled.count);
        maxChannels = 8;
        // Per-band settings and coefficients, then filter state per channel.
        type = 0; freq = 64; gainDB = 128; q = 192;
        cb0 = 256; cb1 = 320; cb2 = 384; ca1 = 448; ca2 = 512;
        s1 = 1024; s2 = 1024 + 64 * maxChannels;

        // BiquadCoefficients(filter:sampleRate:): identity for bands the sample rate can't realise.
        function band(i, t, f, g, qq) local(w0, cosW0, alpha, a, s, b0, b1, b2, a0, a1, a2) (
          type[i] = t; freq[i] = f; gainDB[i] = g; q[i] = qq;
          f > 0 && f < srate / 2 && qq > 0 ? (
            w0 = 2 * $pi * f / srate;
            cosW0 = cos(w0);
            alpha = sin(w0) / (2 * qq);
            a = 10 ^ (g / 40);
            t == 0 ? (
              b0 = 1 + alpha * a; b1 = -2 * cosW0; b2 = 1 - alpha * a;
              a0 = 1 + alpha / a; a1 = -2 * cosW0; a2 = 1 - alpha / a;
            ) : t == 1 ? (
              s = 2 * sqrt(a) * alpha;
              b0 = a * ((a + 1) - (a - 1) * cosW0 + s);
              b1 = 2 * a * ((a - 1) - (a + 1) * cosW0);
              b2 = a * ((a + 1) - (a - 1) * cosW0 - s);
              a0 = (a + 1) + (a - 1) * cosW0 + s;
              a1 = -2 * ((a - 1) + (a + 1) * cosW0);
              a2 = (a + 1) + (a - 1) * cosW0 - s;
            ) : t == 2 ? (
              s = 2 * sqrt(a) * alpha;
              b0 = a * ((a + 1) + (a - 1) * cosW0 + s);
              b1 = -2 * a * ((a - 1) + (a + 1) * cosW0);
              b2 = a * ((a + 1) + (a - 1) * cosW0 - s);
              a0 = (a + 1) - (a - 1) * cosW0 + s;
              a1 = 2 * ((a - 1) - (a + 1) * cosW0);
              a2 = (a + 1) - (a - 1) * cosW0 - s;
            ) : t == 3 ? (
              b0 = (1 - cosW0) / 2; b1 = 1 - cosW0; b2 = (1 - cosW0) / 2;
              a0 = 1 + alpha; a1 = -2 * cosW0; a2 = 1 - alpha;
            ) : t == 4 ? (
              b0 = (1 + cosW0) / 2; b1 = -(1 + cosW0); b2 = (1 + cosW0) / 2;
              a0 = 1 + alpha; a1 = -2 * cosW0; a2 = 1 - alpha;
            ) : (
              b0 = 1; b1 = -2 * cosW0; b2 = 1;
              a0 = 1 + alpha; a1 = -2 * cosW0; a2 = 1 - alpha;
            );
            cb0[i] = b0 / a0; cb1[i] = b1 / a0; cb2[i] = b2 / a0; ca1[i] = a1 / a0; ca2[i] = a2 / a0;
          ) : (
            cb0[i] = 1; cb1[i] = 0; cb2[i] = 0; ca1[i] = 0; ca2[i] = 0;
          );
        );

        \(bands.joined(separator: "\n"))
        memset(s1, 0, 2 * 64 * maxChannels);

        @slider
        gain = 10 ^ (slider1 / 20);

        @sample
        slider2 == 0 ? (
          ch = 0;
          loop(min(num_ch, maxChannels),
            x = spl(ch) * gain;
            i = 0;
            loop(bandCount,
              k = ch * 64 + i;
              y = cb0[i] * x + s1[k];
              s1[k] = cb1[i] * x - ca1[i] * y + s2[k];
              s2[k] = cb2[i] * x - ca2[i] * y;
              x = y;
              i += 1;
            );
            spl(ch) = x;
            ch += 1;
          );
        );

        """
    }
}
